### ISSUE TITLE
Readme: NICS participation map link

### ISSUE THREAD

**Issue by bbrewington** [BuzzFeedNews/nics-firearm-background-checks#2]
I got a page not found when i clicked the link in the readme. Googled to find this link and it works: https://www.fbi.gov/file-repository/nics-participation-map.pdf/view

**Comment by jsvine** [comment]
Thanks! Looks the website changes broke another of the links, too. Fixed both in https://github.com/BuzzFeedNews/nics-firearm-background-checks/commit/beee5113de54642824e77c82dd163f79b24b2a77 and pushed to `master`.

**Comment by timstalder** [comment]
Hello - I was just wondering when the November data will be loaded?

**Comment by jsvine** [comment]
Doh! I could have sworn I pushed it, but looks like I didn't. Fixed that, and now up.

Thanks for flagging!

**Comment by timstalder** [comment]
Awesome!  Thank you!

**Comment by bbrewington** [comment]
There needs to be a DOH emoji :)

![](https://i.pinimg.com/originals/3a/11/68/3a116884945f870924f1ffd3f36fc015.jpg)
